version: '3'

services:
  backend:
    container_name: kafeclope-backend
    image: kafeclope_backend
    build:
      context: ./kafeclope-backend
    command: npm run start:dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./kafeclope-backend:/source
  db:
    container_name: kafeclope-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  pgdata:
 